<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $titlesAndQuestions = [
            [
                'id' => 1,
                'phase_id' => 1,
                'web_id' => '1',
                'question_name_ar' => 'Car Parking',
                'question_name_en' => 'Car Parking',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>[],
                'order'=>1,
                'type' => 'title'
            ],
            [
                'id' => 2,
                'phase_id' => 1,
                'web_id' => '11',
                'question_name_ar' => 'Is private car parking provided?',
                'question_name_en' => 'Is private car parking provided?',
                'description_ar' => 'Only select if you manage or own car parking within your private plot boundary',
                'description_en' => 'Only select if you manage or own car parking within your private plot boundary',
                'answers'=>['yes'=>'','no'=>''],
                'order'=>2,
                'type' => 'question'
            ],
            [
                'id' => 3,
                'phase_id' => 1,
                'web_id' => '12',
                'question_name_ar' => 'What is the total number of car parking spaces?',
                'question_name_en' => 'What is the total number of car parking spaces?',
                'description_ar' => 'This is the total number of spaces provided that you own and manage within your private plot boundary',
                'description_en' => 'This is the total number of spaces provided that you own and manage within your private plot boundary',
                'answers'=>['1-50','51-100','101-200','201-300','301-500','501-600','601-700','701-800','801-900','901-1000','1001-1100','1101-1200','over 1200'],
                'order'=>3,
                'type' => 'question'
            ],
            [
                'id' => 4,
                'phase_id' => 1,
                'web_id' => '13',
                'question_name_ar' => 'Within the 1-50 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 1-50 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['none'=>'','1 or more'=>''],
                'order'=>4,
                'type' => 'question'
            ],
            [
                'id' => 5,
                'phase_id' => 1,
                'web_id' => '14',
                'question_name_ar' => 'Where are disabled car parking spaces located?',
                'question_name_en' => 'Where are disabled car parking spaces located?',
                'description_ar' => 'State if disabled car parking spaces are located on ground floor outside the building or  the basement or other level inside the building? Can select both',
                'description_en' => 'State if disabled car parking spaces are located on ground floor outside the building or  the basement or other level inside the building? Can select both',
                'answers'=>['Outside building'=>asset('/img/questions/image.png'),'Inside building'=>asset('/img/questions/image.png')],
                'order'=>7,
                'type' => 'question'
            ],
            [
                'id' => 6,
                'phase_id' => 1,
                'web_id' => '15',
                'question_name_ar' => 'Are the disabled car parking spaces located close to a building entrance?',
                'question_name_en' => 'Are the disabled car parking spaces located close to a building entrance?',
                'description_ar' => 'State if disabled parking spaces are located closest to the main ground floor entrance (if outside building) or the main car park entrance (if inside the building)',
                'description_en' => 'State if disabled parking spaces are located closest to the main ground floor entrance (if outside building) or the main car park entrance (if inside the building)',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>8,
                'type' => 'question'
            ],
            [
                'id' => 7,
                'phase_id' => 1,
                'web_id' => '16',
                'question_name_ar' => 'Are there any signs to show disabled parking space?',
                'question_name_en' => 'Are there any signs to show disabled parking space?',
                'description_ar' => 'The international symbol of disability may be displayed on a sign attached to wall or post. It may also be painted on the floor of parking space',
                'description_en' => 'The international symbol of disability may be displayed on a sign attached to wall or post. It may also be painted on the floor of parking space',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>9,
                'type' => 'question'
            ],
            [
                'id' => 8,
                'phase_id' => 1,
                'web_id' => '17',
                'question_name_ar' => 'Are there access zones to side of disabled parking spaces?',
                'question_name_en' => 'Are there access zones to side of disabled parking spaces?',
                'description_ar' => 'An access zone is a protected area, that is either painted or has hatched lines, to one or both sides of the disabled parking bay. The zone stops other cars parking close and allows space for disabled people to enter and exit vehicle easily',
                'description_en' => 'An access zone is a protected area, that is either painted or has hatched lines, to one or both sides of the disabled parking bay. The zone stops other cars parking close and allows space for disabled people to enter and exit vehicle easily',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>10,
                'type' => 'question'
            ],
            [
                'id' => 9,
                'phase_id' => 1,
                'web_id' => '18',
                'question_name_ar' => 'Are disabled car parking spaces provided?',
                'question_name_en' => 'Are disabled car parking spaces provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>4,
                'type' => 'question'
            ],
            [
                'id' => 10,
                'phase_id' => 1,
                'web_id' => '19',
                'question_name_ar' => 'Within the [] total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the [] total spaces, how many disabled spaces are provided?',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>1,
                'type' => 'question'
            ],
            [
                'id' => 11,
                'phase_id' => 1,
                'web_id' => '2',
                'question_name_ar' => 'Drop-off Space',
                'question_name_en' => 'Drop-off Space',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>10,
                'type' => 'title'
            ],
            [
                'id' => 12,
                'phase_id' => 1,
                'web_id' => '21',
                'question_name_ar' => 'Is a drop-off space provided within private plot boundary?',
                'question_name_en' => 'Is a drop-off space provided within private plot boundary?',
                'description_ar' => 'A drop-off space is a temporary parking space for private cars or taxis to drop people off close to building entrance',
                'description_en' => 'A drop-off space is a temporary parking space for private cars or taxis to drop people off close to building entrance',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>11,
                'type' => 'question'
            ],
            [
                'id' => 13,
                'phase_id' => 1,
                'web_id' => '22',
                'question_name_ar' => 'Is a drop-off space next to a building entrance?',
                'question_name_en' => 'Is a drop-off space next to a building entrance?',
                'description_ar' => 'A drop-off space should be immediately adjacent to a building entrance or within a very short walk of no longer than 25m',
                'description_en' => 'A drop-off space should be immediately adjacent to a building entrance or within a very short walk of no longer than 25m',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>12,
                'type' => 'question'
            ],
            [
                'id' => 14,
                'phase_id' => 1,
                'web_id' => '23',
                'question_name_ar' => 'Is there a kerb beside drop-off space?',
                'question_name_en' => 'Is there a kerb beside drop-off space?',
                'description_ar' => 'A kerb is the edge of a road that separates the lower road from the raised sidewalk pedestrian area',
                'description_en' => 'A kerb is the edge of a road that separates the lower road from the raised sidewalk pedestrian area',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 15,
                'phase_id' => 1,
                'web_id' => '3',
                'question_name_ar' => 'Route Between Disabled Parking and Entrance',
                'question_name_en' => 'Route Between Disabled Parking and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>14,
                'type' => 'title'
            ],
            [
                'id' => 16,
                'phase_id' => 1,
                'web_id' => '31',
                'question_name_ar' => 'Is the width of the route between disabled spaces and entrance always over 850mm?',
                'question_name_en' => 'Is the width of the route between disabled spaces and entrance always over 850mm?',
                'description_ar' => 'On the entire route between disabled space and entrance, identify if there are any sections where the width of path reduces below 850mm',
                'description_en' => 'On the entire route between disabled space and entrance, identify if there are any sections where the width of path reduces below 850mm',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>15,
                'type' => 'question'
            ],
            [
                'id' => 17,
                'phase_id' => 1,
                'web_id' => '32',
                'question_name_ar' => 'Are there any obstructions on route between disabled spaces and entrance that reduce width of path below 850mm?',
                'question_name_en' => 'Are there any obstructions on route between disabled spaces and entrance that reduce width of path below 850mm?',
                'description_ar' => 'On the entire route between disabled space and entrance, identify if there are temporary or permanent obstructions in the ground that reduce width of path below 850mm',
                'description_en' => 'On the entire route between disabled space and entrance, identify if there are temporary or permanent obstructions in the ground that reduce width of path below 850mm',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>16,
                'type' => 'question'
            ],
            [
                'id' => 18,
                'phase_id' => 1,
                'web_id' => '33',
                'question_name_ar' => 'Are there any uneven surfaces on the route between disabled spaces and entrance?',
                'question_name_en' => 'Are there any uneven surfaces on the route between disabled spaces and entrance?',
                'description_ar' => 'On the entire route between disabled parking and entrance, identify if there are any uneven surfaces that may cause trip hazard for people or be difficult to travel over in a wheelchair. Surfaces may include loose gravel, unfinished areas, sand, crazy paving or stones with large gaps',
                'description_en' => 'On the entire route between disabled parking and entrance, identify if there are any uneven surfaces that may cause trip hazard for people or be difficult to travel over in a wheelchair. Surfaces may include loose gravel, unfinished areas, sand, crazy paving or stones with large gaps',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>17,
                'type' => 'question'
            ],
            [
                'id' => 19,
                'phase_id' => 1,
                'web_id' => '34',
                'question_name_ar' => 'Is there any height obstruction below 2.1m on the route between disabled spaces and entrance?',
                'question_name_en' => 'Is there any height obstruction below 2.1m on the route between disabled spaces and entrance?',
                'description_ar' => 'On the entire route between disabled parking and entrance, identify if there are any obstructions below 2.1m that can be hit with the head by people using path',
                'description_en' => 'On the entire route between disabled parking and entrance, identify if there are any obstructions below 2.1m that can be hit with the head by people using path',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>18,
                'type' => 'question'
            ],
            [
                'id' => 20,
                'phase_id' => 1,
                'web_id' => '35',
                'question_name_ar' => 'Are any of the following present on the route between disabled parking and entrance?',
                'question_name_en' => 'Are any of the following present on the route between disabled parking and entrance?',
                'description_ar' => 'On the entire route between disabled parking and entrance identify if there are any of these change of levels that can cause problems for blind people, low mobility or people in wheelchairs. A drop to side of path should be selected if greater than 600mm in height',
                'description_en' => 'On the entire route between disabled parking and entrance identify if there are any of these change of levels that can cause problems for blind people, low mobility or people in wheelchairs. A drop to side of path should be selected if greater than 600mm in height',
                'answers'=>['Ramp in route'=>asset('/img/questions/image.png'),'Stairs in route'=>asset('/img/questions/image.png'),'Single step in route'=>asset('/img/questions/image.png'),'Drop to side of route'=>asset('/img/questions/image.png')],
                'order'=>19,
                'type' => 'question'
            ],
            [
                'id' => 21,
                'phase_id' => 1,
                'web_id' => '36',
                'question_name_ar' => 'Ramp Between Disabled Space and Entrance',
                'question_name_en' => 'Ramp Between Disabled Space and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>20,
                'type' => 'title'
            ],
            [
                'id' => 22,
                'phase_id' => 1,
                'web_id' => '37',
                'question_name_ar' => 'Is the width of the ramp between disabled space and entrance over 850mm?',
                'question_name_en' => 'Is the width of the ramp between disabled space and entrance over 850mm?',
                'description_ar' => '<div>Measure width of the ramp between handrails. If no handrails are provided, measure the floor space from each edge of the ramp</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>Measure width of the ramp between handrails. If no handrails are provided, measure the floor space from each edge of the ramp</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>21,
                'type' => 'question'
            ],
            [
                'id' => 23,
                'phase_id' => 1,
                'web_id' => '38',
                'question_name_ar' => 'What is length of the ramp in cm?',
                'question_name_en' => 'What is length of the ramp in cm?',
                'description_ar' => '<div>قم بقياس الطول من أسفل المنحدر إلى أعلى المنحدر</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>قم بقياس الطول من أسفل المنحدر إلى أعلى المنحدر</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>22,
                'type' => 'question'
            ],
            [
                'id' => 24,
                'phase_id' => 1,
                'web_id' => '39',
                'question_name_ar' => 'What is height of the ramp in cm?',
                'question_name_en' => 'What is height of the ramp in cm?',
                'description_ar' => '<div>Measure the height from bottom of ramp to top of ramp</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>Measure the height from bottom of ramp to top of ramp</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>23,
                'type' => 'question'
            ],
            [
                'id' => 25,
                'phase_id' => 1,
                'web_id' => '311',
                'question_name_ar' => 'Does the ramp have clear and level landing areas that are larger than 1.5m by 1.5m?',
                'question_name_en' => 'Does the ramp have clear and level landing areas that are larger than 1.5m by 1.5m?',
                'description_ar' => 'A clear landing area allows wheelchair users to manoeuvre easily at top and bottom of ramp',
                'description_en' => 'A clear landing area allows wheelchair users to manoeuvre easily at top and bottom of ramp',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>24,
                'type' => 'question'
            ],
            [
                'id' => 26,
                'phase_id' => 1,
                'web_id' => '312',
                'question_name_ar' => 'Is there a level landing rest area at least every 9m of the ramp?',
                'question_name_en' => 'Is there a level landing rest area at least every 9m of the ramp?',
                'description_ar' => 'A landing area is a level area for people to stop and rest. It must be the width of ramp and at least 1.8m in length',
                'description_en' => 'A landing area is a level area for people to stop and rest. It must be the width of ramp and at least 1.8m in length',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>25,
                'type' => 'question'
            ],
            [
                'id' => 27,
                'phase_id' => 1,
                'web_id' => '4',
                'question_name_ar' => 'Route Between Street and Entrance',
                'question_name_en' => 'Route Between Street and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>26,
                'type' => 'title'
            ],

            [
                'id' => 28,
                'phase_id' => 1,
                'web_id' => '41',
                'question_name_ar' => 'Is the main entrance directly on the street?',
                'question_name_en' => 'Is the main entrance directly on the street?',
                'description_ar' => 'State if main entrance is directly on the building line of the street or if it is set back from street with an external path between street and entrance',
                'description_en' => 'State if main entrance is directly on the building line of the street or if it is set back from street with an external path between street and entrance',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>27,
                'type' => 'question'
            ],
            [
                'id' => 29,
                'phase_id' => 1,
                'web_id' => '42',
                'question_name_ar' => 'Is the width of the route between street and entrance always over 850mm?',
                'question_name_en' => 'Is the width of the route between street and entrance always over 850mm?',
                'description_ar' => 'On the entire route between street and entrance, identify if there are any sections where the width of path reduces below 850mm',
                'description_en' => 'On the entire route between street and entrance, identify if there are any sections where the width of path reduces below 850mm',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>28,
                'type' => 'question'
            ],
            [
                'id' => 30,
                'phase_id' => 1,
                'web_id' => '43',
                'question_name_ar' => 'Are there any obstructions on route between street and entrance that reduce width of path below 850mm?',
                'question_name_en' => 'Are there any obstructions on route between street and entrance that reduce width of path below 850mm?',
                'description_ar' => 'On the entire route between street and entrance, identify if there are temporary or permanent obstructions in the ground that reduce width of path below 850mm',
                'description_en' => 'On the entire route between street and entrance, identify if there are temporary or permanent obstructions in the ground that reduce width of path below 850mm',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>29,
                'type' => 'question'
            ],
            [
                'id' => 31,
                'phase_id' => 1,
                'web_id' => '44',
                'question_name_ar' => 'Are there any uneven surfaces on the route between street and entrance?',
                'question_name_en' => 'Are there any uneven surfaces on the route between street and entrance?',
                'description_ar' => 'On the entire route between street and entrance, identify if there are any uneven surfaces that may cause trip hazard for people or be difficult to travel over in a wheelchair. Surfaces may include loose gravel, unfinished areas, sand, crazy paving or stones with large gaps',
                'description_en' => 'On the entire route between street and entrance, identify if there are any uneven surfaces that may cause trip hazard for people or be difficult to travel over in a wheelchair. Surfaces may include loose gravel, unfinished areas, sand, crazy paving or stones with large gaps',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>30,
                'type' => 'question'
            ],
            [
                'id' => 32,
                'phase_id' => 1,
                'web_id' => '45',
                'question_name_ar' => 'Is there any height obstruction below 2.1m on the route between street and entrance?',
                'question_name_en' => 'Is there any height obstruction below 2.1m on the route between street and entrance?',
                'description_ar' => 'On the entire route between street and entrance, identify if there are any obstructions below 2.1m that can be hit with the head by people using path',
                'description_en' => 'On the entire route between street and entrance, identify if there are any obstructions below 2.1m that can be hit with the head by people using path',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>31,
                'type' => 'question'
            ],
            [
                'id' => 33,
                'phase_id' => 1,
                'web_id' => '46',
                'question_name_ar' => 'Are any of the following present on the route between street and entrance?',
                'question_name_en' => 'Are any of the following present on the route between street and entrance?',
                'description_ar' => 'On the entire route between street and entrance identify if there are any of these change of levels that can cause problems for blind people, low mobility or people in wheelchairs. A drop to side of path should be selected if greater than 600mm in height from floor',
                'description_en' => 'On the entire route between street and entrance identify if there are any of these change of levels that can cause problems for blind people, low mobility or people in wheelchairs. A drop to side of path should be selected if greater than 600mm in height from floor',
                'answers'=>['Ramp in path'=>asset('/img/questions/image.png'),'Stairs in path'=>asset('/img/questions/image.png'),'Single step in path'=>asset('/img/questions/image.png'),'Drop to side of path'=>asset('/img/questions/image.png')],
                'order'=>32,
                'type' => 'question'
            ],
            [
                'id' => 34,
                'phase_id' => 1,
                'web_id' => '5',
                'question_name_ar' => 'Ramp Between Street and Entrance',
                'question_name_en' => 'Ramp Between Street and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>33,
                'type' => 'title'
            ],
            [
                'id' => 35,
                'phase_id' => 1,
                'web_id' => '51',
                'question_name_ar' => 'Is the width of the ramp over 850mm?',
                'question_name_en' => 'Is the width of the ramp over 850mm?',
                'description_ar' => '<div>Measure the width of ramp floor. If there are handrails, measure distance between each handrail</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>Measure the width of ramp floor. If there are handrails, measure distance between each handrail</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>34,
                'type' => 'question'
            ],
            [
                'id' => 36,
                'phase_id' => 1,
                'web_id' => '52',
                'question_name_ar' => 'What is length of the ramp in cm?',
                'question_name_en' => 'What is length of the ramp in cm?',
                'description_ar' => '<div>قم بقياس الطول من أسفل المنحدر إلى أعلى المنحدر</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>قم بقياس الطول من أسفل المنحدر إلى أعلى المنحدر</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>35,
                'type' => 'question'
            ],
            [
                'id' => 37,
                'phase_id' => 1,
                'web_id' => '53',
                'question_name_ar' => 'What is height of the ramp in cm?',
                'question_name_en' => 'What is height of the ramp in cm?',
                'description_ar' => '<div>Measure the height from bottom of ramp to top of ramp</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>Measure the height from bottom of ramp to top of ramp</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>36,
                'type' => 'question'
            ],
            [
                'id' => 38,
                'phase_id' => 1,
                'web_id' => '54',
                'question_name_ar' => 'Does this ramp have clear and level landing areas that are larger than 1.5m by 1.5m?',
                'question_name_en' => 'Does this ramp have clear and level landing areas that are larger than 1.5m by 1.5m?',
                'description_ar' => 'A clear landing area allows wheelchair users to manoeuvre easily at top and bottom of ramp',
                'description_en' => 'A clear landing area allows wheelchair users to manoeuvre easily at top and bottom of ramp',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>37,
                'type' => 'question'
            ],
            [
                'id' => 39,
                'phase_id' => 1,
                'web_id' => '6',
                'question_name_ar' => 'Stairs Between Street and Entrance',
                'question_name_en' => 'Stairs Between Street and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>38,
                'type' => 'title'
            ],
            [
                'id' => 40,
                'phase_id' => 1,
                'web_id' => '61',
                'question_name_ar' => 'Do stairs have handrails?',
                'question_name_en' => 'Do stairs have handrails?',
                'description_ar' => 'A handrail is provided for balance and stability of all users. The upper handrail should be between 875mm - 925mm from floor',
                'description_en' => 'A handrail is provided for balance and stability of all users. The upper handrail should be between 875mm - 925mm from floor',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>39,
                'type' => 'question'
            ],
            [
                'id' => 41,
                'phase_id' => 1,
                'web_id' => '62',
                'question_name_ar' => 'Are handrails on stairs provided at two heights?',
                'question_name_en' => 'Are handrails on stairs provided at two heights?',
                'description_ar' => 'An upper and lower handrail is provided for people at all heights or in wheelchairs. The lower handrail should be between 600mm - 750mm from floor',
                'description_en' => 'An upper and lower handrail is provided for people at all heights or in wheelchairs. The lower handrail should be between 600mm - 750mm from floor',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>40,
                'type' => 'question'
            ],
            [
                'id' => 42,
                'phase_id' => 1,
                'web_id' => '63',
                'question_name_ar' => 'Are tactile warning surfaces provided on stairs?',
                'question_name_en' => 'Are tactile warning surfaces provided on stairs?',
                'description_ar' => '<div>A tactile warning strip is a textured floor paving that alerts blind people about hazard.</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>A tactile warning strip is a textured floor paving that alerts blind people about hazard.</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>41,
                'type' => 'question'
            ],
            [
                'id' => 43,
                'phase_id' => 1,
                'web_id' => '7',
                'question_name_ar' => 'Single Step Between Street and Entrance',
                'question_name_en' => 'Single Step Between Street and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>42,
                'type' => 'title'
            ],
            [
                'id' => 44,
                'phase_id' => 1,
                'web_id' => '71',
                'question_name_ar' => 'Is there an alternative route to entrance to avoid the step?',
                'question_name_en' => 'Is there an alternative route to entrance to avoid the step?',
                'description_ar' => 'A single step can cause trip hazard or difficulty for wheelchair users. State if an alternative step-free route to the entrance is available',
                'description_en' => 'A single step can cause trip hazard or difficulty for wheelchair users. State if an alternative step-free route to the entrance is available',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>43,
                'type' => 'question'
            ],
            [
                'id' => 45,
                'phase_id' => 1,
                'web_id' => '8',
                'question_name_ar' => 'Drop to side of path',
                'question_name_en' => 'Drop to side of path',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>44,
                'type' => 'title'
            ],
            [
                'id' => 46,
                'phase_id' => 1,
                'web_id' => '81',
                'question_name_ar' => 'Is there a guardrail along side of path?',
                'question_name_en' => 'Is there a guardrail along side of path?',
                'description_ar' => 'A drop to side of path of greater than 600mm must be protected with a guardrail to national regulation standards',
                'description_en' => 'A drop to side of path of greater than 600mm must be protected with a guardrail to national regulation standards',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>45,
                'type' => 'question'
            ],
            [
                'id' => 47,
                'phase_id' => 1,
                'web_id' => '120',
                'question_name_ar' => 'Within the 51-100 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 51-100 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['1 or less'=>'','2 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 48,
                'phase_id' => 1,
                'web_id' => '121',
                'question_name_ar' => 'Within the 101-200 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 101-200 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['3 or less'=>'','4 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 49,
                'phase_id' => 1,
                'web_id' => '122',
                'question_name_ar' => 'Within the 201-300 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 201-300 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['4 or less'=>'','5 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 50,
                'phase_id' => 1,
                'web_id' => '123',
                'question_name_ar' => 'Within the 301-500 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 301-500 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['5 or less'=>'','6 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 51,
                'phase_id' => 1,
                'web_id' => '124',
                'question_name_ar' => 'Within the 501-600 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 501-600 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['6 or less'=>'','7 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 52,
                'phase_id' => 1,
                'web_id' => '125',
                'question_name_ar' => 'Within the 601-700 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 601-700 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['7 or less'=>'','8 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 53,
                'phase_id' => 1,
                'web_id' => '126',
                'question_name_ar' => 'Within the 701-800 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 701-800 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['8 or less'=>'','9 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 54,
                'phase_id' => 1,
                'web_id' => '127',
                'question_name_ar' => 'Within the 801-900 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 801-900 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['9 or less'=>'','10 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 55,
                'phase_id' => 1,
                'web_id' => '128',
                'question_name_ar' => 'Within the 901-1000 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 901-1000 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['10 or less'=>'','11 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],

            [
                'id' => 56,
                'phase_id' => 1,
                'web_id' => '129',
                'question_name_ar' => 'Within the 1001-1100 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 1001-1100 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['11 or less'=>'','12 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 57,
                'phase_id' => 1,
                'web_id' => '130',
                'question_name_ar' => 'Within the 1101-1200 total spaces, how many disabled spaces are provided?',
                'question_name_en' => 'Within the 1101-1200 total spaces, how many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['12 or less'=>'','13 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 58,
                'phase_id' => 1,
                'web_id' => '131',
                'question_name_ar' => 'How many disabled spaces are provided?',
                'question_name_en' => 'How many disabled spaces are provided?',
                'description_ar' => 'A designated space used only by disabled people with relevant certification',
                'description_en' => 'A designated space used only by disabled people with relevant certification',
                'answers'=>['13 or less'=>'','14 or more'=>''],
                'order'=>6,
                'type' => 'question'
            ],
            [
                'id' => 59,
                'phase_id' => 1,
                'web_id' => '24',
                'question_name_ar' => 'Is there a kerb cut?',
                'question_name_en' => 'Is there a kerb cut?',
                'description_ar' => 'A kerb-cut is a sloped area that connects the raised pedestrian area with road and avoids need to climb up the step',
                'description_en' => 'A kerb-cut is a sloped area that connects the raised pedestrian area with road and avoids need to climb up the step',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 60,
                'phase_id' => 1,
                'web_id' => '313',
                'question_name_ar' => 'Stairs Between Disabled Space and Entrance',
                'question_name_en' => 'Stairs Between Disabled Space and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>26,
                'type' => 'title'
            ],
            [
                'id' => 61,
                'phase_id' => 1,
                'web_id' => '314',
                'question_name_ar' => 'Do the stairs have handrails?',
                'question_name_en' => 'Do the stairs have handrails?',
                'description_ar' => 'A handrail is provided for balance and stability of all users. The upper handrail should be between 875mm - 925mm from floor',
                'description_en' => 'A handrail is provided for balance and stability of all users. The upper handrail should be between 875mm - 925mm from floor',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 62,
                'phase_id' => 1,
                'web_id' => '315',
                'question_name_ar' => 'Are the handrails on stairs provided at two heights?',
                'question_name_en' => 'Are the handrails on stairs provided at two heights?',
                'description_ar' => 'An upper and lower handrail is provided for people at all heights or in wheelchairs. The lower handrail should be between 600mm - 750mm from floor',
                'description_en' => 'An upper and lower handrail is provided for people at all heights or in wheelchairs. The lower handrail should be between 600mm - 750mm from floor',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 63,
                'phase_id' => 1,
                'web_id' => '316',
                'question_name_ar' => 'Are there tactile warning surfaces provided on stairs?',
                'question_name_en' => 'Are there tactile warning surfaces provided on stairs?',
                'description_ar' => '<div>A tactile warning strip is a textured floor paving that alerts blind people about hazard.</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'description_en' => '<div>A tactile warning strip is a textured floor paving that alerts blind people about hazard.</div> <img src="' . (asset('/img/questions/image.png')) . '" style="width: 100px">',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 64,
                'phase_id' => 1,
                'web_id' => '317',
                'question_name_ar' => 'Single Step Between Disabled Space and Entrance',
                'question_name_en' => 'Single Step Between Disabled Space and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>26,
                'type' => 'title'
            ],
            [
                'id' => 65,
                'phase_id' => 1,
                'web_id' => '318',
                'question_name_ar' => 'Is there an alternative route to the entrance to avoid the step?',
                'question_name_en' => 'Is there an alternative route to the entrance to avoid the step?',
                'description_ar' => 'A single step can cause trip hazard or difficulty for wheelchair users. State if an alternative step-free route to the entrance is available',
                'description_en' => 'A single step can cause trip hazard or difficulty for wheelchair users. State if an alternative step-free route to the entrance is available',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],

            [
                'id' => 66,
                'phase_id' => 1,
                'web_id' => '319',
                'question_name_ar' => 'Drop to side of path Between Disabled Space and Entrance',
                'question_name_en' => 'Drop to side of path Between Disabled Space and Entrance',
                'description_ar' => '',
                'description_en' => '',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>26,
                'type' => 'title'
            ],
            [
                'id' => 67,
                'phase_id' => 1,
                'web_id' => '320',
                'question_name_ar' => 'Is there a guardrail along the side of path?',
                'question_name_en' => 'Is there a guardrail along the side of path?',
                'description_ar' => 'A drop to side of path of greater than 600mm must be protected with a guardrail to national regulation standards',
                'description_en' => 'A drop to side of path of greater than 600mm must be protected with a guardrail to national regulation standards',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 68,
                'phase_id' => 1,
                'web_id' => '55',
                'question_name_ar' => 'Is there a level landing rest area at least every 9m of this ramp?',
                'question_name_en' => 'Is there a level landing rest area at least every 9m of this ramp?',
                'description_ar' => 'A landing area is a level area for people to stop and rest. It must be the width of ramp and at least 1.8m in length',
                'description_en' => 'A landing area is a level area for people to stop and rest. It must be the width of ramp and at least 1.8m in length',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 69,
                'phase_id' => 1,
                'web_id' => '56',
                'question_name_ar' => 'Does this ramp have handrails?',
                'question_name_en' => 'Does this ramp have handrails?',
                'description_ar' => 'A handrail is provided for balance and stability of all users. The upper handrail should be between 875mm - 925mm from floor',
                'description_en' => 'A handrail is provided for balance and stability of all users. The upper handrail should be between 875mm - 925mm from floor',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 60,
                'phase_id' => 1,
                'web_id' => '57',
                'question_name_ar' => 'Are handrails provided at two heights on this ramp?',
                'question_name_en' => 'Are handrails provided at two heights on this ramp?',
                'description_ar' => 'An upper and lower handrail is provided for people at all heights or in wheelchairs. The lower handrail should be between 600mm - 750mm from floor',
                'description_en' => 'An upper and lower handrail is provided for people at all heights or in wheelchairs. The lower handrail should be between 600mm - 750mm from floor',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 60,
                'phase_id' => 1,
                'web_id' => '58',
                'question_name_ar' => 'Does this ramp have clear and level landing areas that are larger than 1.5m by 1.5m?',
                'question_name_en' => 'Does this ramp have clear and level landing areas that are larger than 1.5m by 1.5m?',
                'description_ar' => 'A clear landing area allows wheelchair users to manoeuvre easily at top and bottom of ramp',
                'description_en' => 'A clear landing area allows wheelchair users to manoeuvre easily at top and bottom of ramp',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 60,
                'phase_id' => 1,
                'web_id' => '59',
                'question_name_ar' => 'Is there any alternative route to entrance from the street without using ramp?',
                'question_name_en' => 'Is there any alternative route to entrance from the street without using ramp?',
                'description_ar' => 'State if there is an alternative level and wide route for people to use to avoid this ramp',
                'description_en' => 'State if there is an alternative level and wide route for people to use to avoid this ramp',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 60,
                'phase_id' => 1,
                'web_id' => '24',
                'question_name_ar' => 'xxxxx',
                'question_name_en' => 'xxxxx',
                'description_ar' => 'yyyyy',
                'description_en' => 'yyyyy',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
            [
                'id' => 60,
                'phase_id' => 1,
                'web_id' => '24',
                'question_name_ar' => 'xxxxx',
                'question_name_en' => 'xxxxx',
                'description_ar' => 'yyyyy',
                'description_en' => 'yyyyy',
                'answers'=>['yes'=>asset('/img/questions/image.png'),'no'=>asset('/img/questions/image.png')],
                'order'=>13,
                'type' => 'question'
            ],
        ];
        foreach ($titlesAndQuestions as $titleAndQuestion) {
            $jsonString = json_encode($titleAndQuestion['answers'] );

            Question::updateorcreate(
                ['id' => $titleAndQuestion['id']],
                [
                    'id' => $titleAndQuestion['id'],
                    'phase_id' => $titleAndQuestion['phase_id'],
                    'web_id' => $titleAndQuestion['web_id'],
                    'question_name_ar' => $titleAndQuestion['question_name_ar'],
                    'question_name_en' => $titleAndQuestion['question_name_en'],
                    'description_ar' => $titleAndQuestion['description_ar'],
                    'description_en' => $titleAndQuestion['description_en'],
                    'answers' => $jsonString,
                    'order' => $titleAndQuestion['order'],
                    'type' => $titleAndQuestion['type'],
                ],
            );
        }
    }
}
